# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
# NOTE: This is a *kustomize* Kustomization (kustomize.config.k8s.io) consumed by Flux's kustomize-controller.
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring.yaml
