apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actualbudget
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/actualbudget # Path to the app's Kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  timeout: 5m
  dependsOn:
    - name: ingress-nginx
