---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: audiobookshelf
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/audiobookshelf
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  timeout: 5m
  dependsOn:
    - name: infra-storage-media
    - name: ingress-nginx
