# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: calibre-web-automated
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/calibre-web-automated # Path to the calibre-web-automated app's Kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default # Namespace where calibre-web-automated app runs
  timeout: 5m
  dependsOn:
    - name: infra-storage-media
    - name: infra-storage-calibre
    - name: ingress-nginx
