# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ersatztv
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/ersatztv
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  timeout: 5m
  dependsOn:
    - name: democratic-csi
    - name: infra-storage-media
    - name: ingress-nginx

