# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: exposure-control
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/exposure-control
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  timeout: 5m
  dependsOn:
    - name: public-edge
    - name: ingress-nginx
    - name: cert-manager
    - name: external-dns
