---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: glance
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/glance
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  timeout: 5m
  dependsOn:
    - name: ingress-nginx
    - name: external-dns
