---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lan-access
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/lan-gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  timeout: 5m
  dependsOn:
    - name: ingress-nginx
    - name: external-dns
