# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: resource-advisor
  namespace: flux-system
spec:
  interval: 30m
  path: ./infrastructure/resource-advisor
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  dependsOn:
    - name: monitoring
