# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
# NOTE: This is a *kustomize* Kustomization (kustomize.config.k8s.io).
# It currently uses apiVersion v1beta1; Flux's Kustomization CRD is separate (kustomize.toolkit.fluxcd.io/v1).
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager
  - ./default
  - ./democratic-csi
  - ./flux-system
  - ./monitoring
  - ./public-edge
  - ./tailscale
