---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blog-image-repository.yaml
  - blog-image-policy.yaml
  - mmcal-image-repository.yaml
  - mmcal-image-policy.yaml
  - image-update-automation.yaml
