# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
# NOTE: This is a *kustomize* Kustomization (kustomize.config.k8s.io) and must be compatible with `kubectl kustomize`.
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homepage-widget-secrets.yaml
  - immich-db-secret.yaml
  - jellystat-app-secret.yaml
  - jellystat-db-secret.yaml
  - media-postgres-secret.yaml
  - notifiarr-api-key.yaml
  - notifiarr-ui-password.yaml
  - tracerr-app-secret.yaml
  - tracerr-db-secret.yaml
