---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - report-configmap.yaml
  - cronjob-report.yaml
  - cronjob-pr.yaml
configMapGenerator:
  - name: resource-advisor-script
    files:
      - advisor.py
generatorOptions:
  disableNameSuffixHash: true
