# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - cronjob-report.yaml
  - cronjob-apply-pr.yaml
  - deployment-exporter.yaml
  - service-exporter.yaml
  - ingress-exporter.yaml
  - servicemonitor-exporter.yaml
  - grafana-dashboard-resource-advisor.yaml
configMapGenerator:
  - name: resource-advisor-script
    files:
      - advisor.py
      - exporter.py
generatorOptions:
  disableNameSuffixHash: true
