# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.0-standalone-strict/configmap-v1.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-advisor-latest
  namespace: monitoring
data:
  latest.json: "{}"
  latest.md: |
    # Resource Advisor
  mode: "init"
  lastRunAt: ""
