# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
# NOTE: This is a *kustomize* Kustomization (kustomize.config.k8s.io) and must be compatible with `kubectl kustomize`.
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflared-tunnel-token.yaml
