# yaml-language-server: $schema=https://raw.githubusercontent.com/community-charts/helm-charts/main/charts/actualbudget/values.schema.json
---
image:
  repository: actualbudget/actual-server
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 5006

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

nodeSelector:
  kubernetes.io/hostname: talos-7nf-osf

ingress:
  enabled: true
  className: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: actual.khzaw.dev
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: actual.khzaw.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: actual-tls
      hosts:
        - actual.khzaw.dev

persistence:
  enabled: true
  storageClass: truenas-nfs
  size: 2Gi
  accessModes:
    - ReadWriteOnce

strategy:
  type: Recreate
